from time import time as get_time

from utility.printable import Printable

class Block(Printable):
    """A single block of our blockchain.
    
    Attributes:
        :index: The index of this block.
        :previous_hash: The hash of the previous block in the blockchain.
        :timestamp: The timestamp of the block (automatically generated by default).
        :transactions: A list of transaction which are included in the block.
        :proof: The proof of work number that yielded this block.
        :bits: represents the target for difficulty. Stored as decimal 
        :difficulty: scaled difficulty compared to gensis block with 1.0
    """
    def __init__(self, index, previous_hash, transactions, proof, bits, time=None):
        self.index = index
        self.previous_hash = previous_hash
        if time != None:
            self.timestamp = time
        else:
            self.timestamp = get_time()
        self.transactions = transactions
        self.proof = proof
        self.bits = bits


